import 'package:hive/hive.dart';

part 'subtype.g.dart';

@HiveType(typeId: 4)
enum SubType {
  @HiveField(0)
  none,
  @HiveField(1)
  sword,
  @HiveField(2)
  axe,
  @HiveField(3)
  blunt,
  @HiveField(4)
  cloth,
  @HiveField(5)
  leather,
  @HiveField(6)
  chain,
  @HiveField(7)
  plate,
  @HiveField(8)
  staff,
  @HiveField(9)
  dagger,
  @HiveField(10)
  wand,
  @HiveField(11)
  bow,
  @HiveField(12)
  shield,
  @HiveField(13)
  twoHSword,
  @HiveField(14)
  twoHAxe,
  @HiveField(15)
  twoHBlunt,
  @HiveField(16)
  quiver,
  @HiveField(17)
  offhandDagger,
  @HiveField(18)
  offhandSword,
  @HiveField(19)
  spear,
  @HiveField(20)
  totem,
  @HiveField(21)
  broom,
  @HiveField(22)
  sled,
  @HiveField(23)
  handToHand,
  @HiveField(24)
  fashion,
  @HiveField(25)
  jewelry,
  @HiveField(26)
  carpet,
  @HiveField(27)
  noveltyBroom,
  @HiveField(28)
  noveltyWand,
  @HiveField(29)
  lute,
  @HiveField(30)
  dragonStaff,
  @HiveField(31)
  flute,
  @HiveField(32)
  harp,
  @HiveField(33)
  twoHNovelty,
  @HiveField(34)
  noveltyStaffMount,
  @HiveField(35)
  horn,
  @HiveField(36)
  noveltyBlunt,
  @HiveField(37)
  batMount,
  @HiveField(38)
  wings,
  @HiveField(39)
  drum,
  @HiveField(40)
  bagpipes,
  @HiveField(41)
  eagleMount,
  @HiveField(42)
  test,
  @HiveField(43)
  crow,
  @HiveField(44)
  sparrow,
  @HiveField(45)
  sparrowhawk,
  @HiveField(46)
  cape,
  @HiveField(47)
  horse,
  @HiveField(48)
  bansheeBlade,
  @HiveField(49)
  samhainCrow,
  @HiveField(50)
  samhainWings,
  @HiveField(51)
  playDead,
  @HiveField(52)
  banner,
  @HiveField(53)
  boar,
  @HiveField(54)
  fishingRod,
  @HiveField(55)
  longTotem,
  @HiveField(56)
  offhandBook,
  @HiveField(57)
  twoHSpear,
  @HiveField(58)
  petFood,
  @HiveField(59)
  fishingItem,
  @HiveField(60)
  token,
  @HiveField(61)
  consumable,
  @HiveField(62)
  battleMount,
  @HiveField(63)
  battleMountWand,
  @HiveField(64)
  battleMountBow,
  @HiveField(65)
  battleMountUnarmed,
  @HiveField(66)
  cooking
}
